[portal]
base_url = "http://localhost:3000"

[tiers]
claimed = ["T1", "T2"]
pitch = "VERA: Verifiable Evaluation & Ranking Assistant"

[auth]
organizer   = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..REvzo_1r0V2UApRl.2WDamJ6SFSTU5_j3XBM015CMTrJZOCk_LyuOmN6An2hN0p0K_qfjPIL1ESJnLDLF7iXgBo4JaDz0ozUeChg71gnX8YkicnR3_9o9OmldkWAa5WpHA5dRY-7VdECyafW-2vdicgvOmiFNc58yd_BPjgEn1nhTkeJ12JFkLEouAWDY_vhp7z1Jop1fVrBboGSB-U_AVyJUhqBd7XmJPWTEuwDiWmssHQJ0OqxSgi5fSI0jXCKMXomx.9MogF9kjrHLgilJDvlXWfQ"
judge_a     = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Q8Km7k10f5n3JhbW.NLCvfbJHYNkby06aHS6XnXqiu42anIQ1chWHDFFzF5RmslmslvlorhQ7BHcfvYMqsjj3UwDPB9-qdDLPwBDdEhbPgBTZowZT0N1e_XwiENEsYs6nEPL71uxp-DUpbOm_COUbf4dQXWsxNhg-pECDEmE6CUnxRAuOD2VXXp3tHNUMCpZad7NiRVsKhAUbGhik0x7xyuFA48hWh-uOddMCOTGUOU9vi5a12ogJDHUohF1WnE5n8ZbUOULCXDULdfsKzDTzEbHkWeJO1oZdfX0G.GigqiXQahESLsENjJRm5Qg"
judge_b     = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..8I7QKNMOdhykDYkz.J_f91cZnMOBajIPJxHME8_8dIQE6SOkYgzqv3HK51Qq6eZdl-0JyY-4smUv957K0Fgp5kgnUz4tRmp2BVZVi86CdkkjUjaruuuPAdKInqFjTkOJylIPf6j6SvG9qLvCCmgAEYWpqyv5X5pDX6UW809FyjB5nz_j5e9ZqZjKlwdEdzHsVMTtjxnf_rwy17otr18hXZ8whRS5MawZDp6CUJbcovu1BWm1Qnq6vtwn41FmBWOXRVGj-IKMkXN6i0Iz2bGtwYrGjzXYXm0TiZR_5qk0o-SUFbmE_BBKWlDabpA.eNaJqcQluWNJHeSsUKlEyQ"
participant = "Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0.._Op9EhP3EeBsRzcq.hSI98ePo-JlpDRl4MGs3bdgnAjt2uWtynXEnQYCAPZ6053sNkCkHQSvTZuh60gKCRa5sY0SwEyRtcdT2aaXhSE47WpdRYmDHurziIhHdhHTY0D1yCbVvpP2Q35QlhVQLNfFniR5YmqNN_8gmrQVY7dxXJb3ehfzmnevgo3iAOQISgBFFsoE_aMifhpIM8QLQBJpnxdnly3rOj6lhNipn3_-MOc0s1TnvsncEG3iPwEst7DBogc0J2Qg.EHl5qx_694Tb_kuO-DndFg"

[routes]
gallery      = "/api/submissions"
submit       = "/api/submissions"
judge_scores = "/api/judge/scores"
peer_scores  = "/api/judge/scores?judgeId=cmul8g7n50002zly1mig1iyz3"
csv_export   = "/api/organizer/export?type=scores"
